// Generated by CoffeeScript 1.12.4
(function() {
  var Metrics, MetricsRouter;

  MetricsRouter = require('./app/js/MetricsRouter');

  module.exports = Metrics = {
    router: MetricsRouter
  };

}).call(this);
