import React, { useRef, useEffect, useState } from 'react'
import PropTypes from 'prop-types'
import Linkify from 'react-linkify'

function MessageContent({ content }) {
  const root = useRef(null)

  const [MJHub, setMJHub] = useState(undefined)
  useEffect(() => {
    import('../../../MathJaxBundle')
      .then(({ default: MathJax }) => {
        setMJHub(MathJax.Hub)
      })
      .catch(error => console.error('Cannot load MathJaxBundle', error))
  }, [])

  useEffect(
    () => {
      // adds attributes to all the links generated by <Linkify/>, required due to https://github.com/tasti/react-linkify/issues/99
      for (let a of root.current.getElementsByTagName('a')) {
        a.setAttribute('target', '_blank')
        a.setAttribute('rel', 'noreferrer noopener')
      }

      // MathJax typesetting
      if (!MJHub) return
      const timeoutHandler = setTimeout(() => {
        MJHub.Queue(['Typeset', MJHub, root.current])
      }, 0)
      return () => clearTimeout(timeoutHandler)
    },
    [content, MJHub]
  )

  return (
    <p ref={root}>
      <Linkify>{content}</Linkify>
    </p>
  )
}

MessageContent.propTypes = {
  content: PropTypes.string.isRequired
}

export default MessageContent
