// Generated by CoffeeScript 1.12.4
(function() {
  var MockOverleafApi, _mockTemplate, app, bodyParser, express, sinon;

  express = require("express");

  app = express();

  bodyParser = require('body-parser');

  sinon = require('sinon');

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  module.exports = MockOverleafApi = {
    run: function() {
      app.get("/latex/templates/-/redirect-article", (function(_this) {
        return function(req, res, next) {
          return res.json(_mockTemplate({
            open_in_v2_links: {
              main: {
                v2: '/redirect'
              }
            }
          }));
        };
      })(this));
      return app.listen(5000, function(error) {
        if (error != null) {
          throw error;
        }
      }).on("error", function(error) {
        console.error("error starting MockOverleafApi:", error.message);
        return process.exit(1);
      });
    }
  };

  MockOverleafApi.run();

  _mockTemplate = function(data) {
    return Object.assign({}, {
      pdf_links: {
        main: {
          pdf: "/pdf"
        }
      },
      pub: {
        kind: "template"
      }
    }, data);
  };

}).call(this);
